### ISSUE TITLE
Style Login page

### ISSUE THREAD

**Issue by elenirotsides** [elenirotsides/Gyro#34]
Make the login page a little better to look at, maybe add a break in between the email and password so the inputs aren't horizontal

**Comment by derobertsw** [comment]
I split email/password onto separate lines as part of the accessibility user story.  I don't know if we want to do more styling on top of that

**Comment by elenirotsides** [comment]
Perhaps we can center the login/register page?

**Comment by elenirotsides** [comment]
And adjust fonts/colors depending on what's going on. If there's an error, that could be red.
