### ISSUE TITLE
BUG: Improve the search feature

### ISSUE THREAD

**Issue by elenirotsides** [elenirotsides/Gyro#41]
There are a few things wrong with the search feature:

- Currently, you cannot search by title. Searching by tags **does** work though, so that's good
- We need some kind of back button or clear button that reverts the view into the /board view. After the user does a search, the only way to go back to the board is by deleting the query in the url, ex/ going from http://localhost:3000/board?query=bug to http://localhost:3000/board

**Comment by derobertsw** [comment]
Added clear filter button
