### ISSUE TITLE
BUG: tasksCreated not populating data in the db

### ISSUE THREAD

**Issue by elenirotsides** [elenirotsides/Gyro#43]
In the Users collection in the database, `tasksCreated` is currently not being populated with data even though the users have indeed created tasks. Is this something that needs to get done in the routes when `addTask` is being called?

Edit: We're better off removing that field from the db since we don't use it and currently doesn't serve us a purpose

**Comment by derobertsw** [comment]
I don't think we use `tasksCreated` anywhere.  I think it'd be better to drop that field from the db vs implementing it

**Comment by elenirotsides** [comment]
I agree, we have no use for it anyway
