### ISSUE TITLE
BUG: When adding a task, if you do not provide a tag, the page does not load properly

### ISSUE THREAD

**Issue by cbickler** [elenirotsides/Gyro#47]
the task is also not created, not sure what is causing this. You are able to create a task with a tag no problem, but if you do not add a tag this is what the page loads below. This is after clicking submit.
![image](https://user-images.githubusercontent.com/37080132/90713769-108d4980-e274-11ea-8c9f-cf3214a83882.png)

We could also solve this by just making it a requirement to add at least one tag?

**Comment by elenirotsides** [comment]
This must be caused by my create route not rendering the correct page, I can take a look tmr!
