### ISSUE TITLE
Create post routes

### ISSUE THREAD

**Issue by derobertsw** [elenirotsides/Gyro#6]

**Comment by elenirotsides** [comment]
/login
/register
/tasks/
/tasks/create
/tasks/ID/edit
/tasks/ID/remove
/tasks/ID/drag (AJAX from drag)
/tasks/ID/comments
/tasks/ID/comments/create

**Comment by elenirotsides** [comment]
I lumped all the above POST routes and work associated with it in this issue...not the best way to organize the work I know

**Comment by elenirotsides** [comment]
**Done:** 
/login
/register
/tasks/create

**Comment by elenirotsides** [comment]
Did most of the POST routes, left the rest up to the team
