### ISSUE TITLE
XSS Validation Middleware

### ISSUE THREAD

**Issue by wessles** [elenirotsides/Gyro#8]
Make sure to wrap request body in xss!!

-the above is wrong. You have to wrap each individual input in xss, NOT the request body

**Comment by elenirotsides** [comment]
@wessles For the code I'm submitting, I'm wrapping my inputs with xss. What would the middleware accomplish?

**Comment by wessles** [comment]
I see. I misunderstood.

**Comment by elenirotsides** [comment]
No worries!

**Comment by wessles** [comment]
Actually, I take it back. This can be implemented and will simplify the code. Re-opening.
